backend:
  name: git-gateway
  branch: main
media_folder: "img/uploads"
slug:
  encoding: "ascii"
  clean_accents: true
collections:
  - name: "blog"
    label: "blog"
    folder: "blog"
    create: true
    slug: "{{year}}{{month}}{{day}}_{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/sablona__blog.njk"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "blog"}
      - {label: "Titulek", name: "title", widget: "string"}
      - {label: "Datum publikace", name: "date", widget: "datetime"}
      - {label: "Obrázek", name: "foto", widget: "image", required: false }
      - {label: "Perex", name: "perex", widget: "string"}
      - {label: "Obsah", name: "body", widget: "markdown"}